@export()
@description('Default abbreviations for resources')
var defaultAbbreviations = {
  // AI + machine learning
  'Microsoft.Search/searchServices': 'srch'
  'Microsoft.MachineLearningServices/workspaces (kind: Hub)': 'hub'
  'Microsoft.MachineLearningServices/workspaces (kind: Project)': 'proj'
  'Microsoft.VideoIndexer/accounts': 'avi'
  'Microsoft.MachineLearningServices/workspaces': 'mlw'
  'Microsoft.BotService/botServices (kind: azurebot)': 'bot'
  'Microsoft.CognitiveServices/accounts': {
    '*': 'cog'
    cognitiveServices: 'cog'
    AIServices: 'ais'
    OpenAi: 'oai'
    ComputerVision: 'cv'
    ContentModerator: 'cm'
    ContentSafety: 'cs'
    CustomVisionPrediction: 'cstv'
    CustomVisionTraining: 'cstvt'
    FormRecognizer: 'di'
    Face: 'face'
    HealthInsights: 'hi'
    ImmersiveReader: 'ir'
    TextAnalytics: 'lang'
    SpeechServices: 'spch'
    TextTranslation: 'trsl'
  }

  // Analytics and IoT
  'Microsoft.AnalysisServices/servers': 'as'
  'Microsoft.Databricks/workspaces': 'dbw'
  'Microsoft.Kusto/clusters': 'dec'
  'Microsoft.Kusto/clusters/databases': 'dedb'
  'Microsoft.DataFactory/factories': 'adf'
  'Microsoft.DigitalTwins/digitalTwinsInstances': 'dt'
  'Microsoft.StreamAnalytics/cluster': 'asa'
  'Microsoft.Synapse/privateLinkHubs': 'synplh'
  'Microsoft.Synapse/workspaces/sqlPools': 'syndp'
  'Microsoft.Synapse/workspaces/bigDataPools': 'synsp'
  'Microsoft.Synapse/workspaces': 'synw'
  'Microsoft.DataLakeStore/accounts': 'dls'
  'Microsoft.DataLakeAnalytics/accounts': 'dla'
  'Microsoft.EventHub/namespaces': 'evhns'
  'Microsoft.EventHub/namespaces/eventHubs': 'evh'
  'Microsoft.EventGrid/domains': 'evgd'
  'Microsoft.EventGrid/eventSubscriptions': 'evgs'
  'Microsoft.EventGrid/domains/topics': 'evgt'
  'Microsoft.EventGrid/systemTopics': 'egst'
  'Microsoft.HDInsight/clusters (kind: Hadoop)': 'hadoop'
  'Microsoft.HDInsight/clusters (kind: HBase)': 'hbase'
  'Microsoft.HDInsight/clusters (kind: Kafka)': 'kafka'
  'Microsoft.HDInsight/clusters (kind: Spark)': 'spark'
  'Microsoft.HDInsight/clusters (kind: Storm)': 'storm'
  'Microsoft.HDInsight/clusters (kind: MLServices)': 'mls'
  'Microsoft.Devices/IotHubs': 'iot'
  'Microsoft.Devices/provisioningServices': 'provs'
  'Microsoft.Devices/provisioningServices/certificates': 'pcert'
  'Microsoft.PowerBIDedicated/capacities': 'pbi'
  'Microsoft.TimeSeriesInsights/environments': 'tsi'

  // Compute and Web
  'Microsoft.Web/hostingEnvironments': 'host'
  // 'Microsoft.Web/hostingEnvironments': 'ase'
  'Microsoft.Web/serverFarms': 'asp'
  'Microsoft.LoadTestService/loadTests': 'lt'
  'Microsoft.Compute/availabilitySets': 'avail'
  'Microsoft.HybridCompute/machines': 'arcs'
  'Microsoft.Kubernetes/connectedClusters': 'arck'
  'Microsoft.HybridCompute/privateLinkScopes': 'pls'
  'Microsoft.HybridCompute/gateways': 'arcgw'
  'Microsoft.Batch/batchAccounts': 'ba'
  'Microsoft.Compute/cloudServices': 'cld'
  'Microsoft.Communication/communicationServices': 'acs'
  'Microsoft.Compute/diskEncryptionSets': 'des'
  'Microsoft.Compute/galleries': 'gal'
  'Microsoft.VirtualMachineImages/imageTemplates': 'it'

  'Microsoft.Web/sites': {
    '*': 'app'
    app: 'app'
    functionApp: 'func'
  }

  'Microsoft.Compute/disks': {
    '*': 'disk'
    Data: 'disk'
    OS: 'osdisk'
  }

  'Microsoft.NotificationHubs/namespaces/notificationHubs': 'ntf'
  'Microsoft.NotificationHubs/namespaces': 'ntfns'
  'Microsoft.Compute/proximityPlacementGroups': 'ppg'
  'Microsoft.Compute/restorePointCollections': 'rpc'
  'Microsoft.Compute/snapshots': 'snap'
  'Microsoft.Web/staticSites': 'stapp'
  'Microsoft.Compute/virtualMachines': 'vm'
  'Microsoft.Compute/virtualMachineScaleSets': 'vmss'
  'Microsoft.Maintenance/maintenanceConfigurations': 'mc'
  'Microsoft.Storage/storageAccounts (kind: VMStorage)': 'stvm'

  // Containers
  'Microsoft.ContainerService/managedClusters': 'aks'
  'Microsoft.ContainerService/managedClusters/agentPools (mode: System)': 'npsystem'
  'Microsoft.ContainerService/managedClusters/agentPools (mode: User)': 'np'
  'Microsoft.App/containerApps': 'ca'
  'Microsoft.App/managedEnvironments': 'cae'
  'Microsoft.ContainerRegistry/registries': 'cr'
  'Microsoft.ContainerInstance/containerGroups': 'ci'
  'Microsoft.ServiceFabric/clusters': 'sf'
  'Microsoft.ServiceFabric/managedClusters': 'sfmc'

  // Databases
  'Microsoft.DocumentDB/databaseAccounts/sqlDatabases': 'cosmos'
  'Microsoft.DocumentDB/databaseAccounts (kind: ApacheCassandra)': 'coscas'
  'Microsoft.DocumentDB/databaseAccounts (kind: MongoDB)': 'cosmon'
  'Microsoft.DocumentDB/databaseAccounts (kind: NoSQL)': 'cosno'
  'Microsoft.DocumentDB/databaseAccounts (kind: Table)': 'costab'
  'Microsoft.DocumentDB/databaseAccounts (kind: ApacheGremlin)': 'cosgrm'
  'Microsoft.DBforPostgreSQL/serverGroupsv2': 'cospos'
  'Microsoft.Cache/Redis': 'redis'
  'Microsoft.Sql/servers': 'sql'
  'Microsoft.Sql/servers/databases': 'sqldb'
  'Microsoft.Sql/servers/jobAgents': 'sqlja'
  'Microsoft.Sql/servers/elasticpool': 'sqlep'
  'Microsoft.DBforMariaDB/servers': 'maria'
  'Microsoft.DBforMariaDB/servers/databases': 'mariadb'
  'Microsoft.DBforMySQL/servers': 'mysql'
  'Microsoft.DBforPostgreSQL/servers': 'psql'
  'Microsoft.Sql/servers/databases (kind: StretchDatabase)': 'sqlstrdb'
  'Microsoft.Sql/managedInstances': 'sqlmi'

  // Developer tools
  'Microsoft.AppConfiguration/configurationStores': 'appcs'
  'Microsoft.Maps/accounts': 'map'
  'Microsoft.SignalRService/SignalR': 'sigr'
  'Microsoft.SignalRService/webPubSub': 'wps'

  // DevOps
  'Microsoft.Dashboard/grafana': 'amg'

  // Integration
  'Microsoft.ServiceBus/namespaces': 'sbns'
  'Microsoft.ServiceBus/namespaces/queues': 'sbq'
  'Microsoft.ServiceBus/namespaces/topics': 'sbt'
  'Microsoft.ServiceBus/namespaces/topics/subscriptions': 'sbts'

  // Management and governance
  'Microsoft.Automation/automationAccounts': 'aa'
  'Microsoft.Authorization/policyDefinitions': '<descriptive>'
  'Microsoft.Insights/components': 'appi'
  'Microsoft.Insights/actionGroups': 'ag'
  'Microsoft.Insights/dataCollectionRules': 'dcr'
  'Microsoft.AlertsManagement/actionRules': 'apr'
  'Microsoft.Blueprint/blueprints': 'bp'
  'Microsoft.Blueprint/blueprints/artifacts': 'bpa'
  'Microsoft.Insights/dataCollectionEndpoints': 'dce'
  'Microsoft.OperationalInsights/workspaces': 'log'
  'Microsoft.OperationalInsights/querypacks': 'pack'
  'Microsoft.Management/managementGroups': 'mg'
  'Microsoft.Purview/accounts': 'pview'
  'Microsoft.Resources/resourceGroups': 'rg'
  'Microsoft.Resources/templateSpecs': 'ts'

  // Migration
  'Microsoft.Migrate/assessmentProjects': 'migr'
  'Microsoft.DataMigration/services': 'dms'
  'Microsoft.RecoveryServices/vaults': 'rsv'

  // Networking
  'Microsoft.Network/applicationGateways': 'agw'
  'Microsoft.Network/applicationSecurityGroups': 'asg'
  'Microsoft.Cdn/profiles': 'cdnp'
  'Microsoft.Cdn/profiles/endpoints': 'cdne'
  'Microsoft.Network/connections': 'con'
  'Microsoft.Network/dnsZones': '<DNS domain name>'
  'Microsoft.Network/dnsForwardingRulesets': 'dnsfrs'
  'Microsoft.Network/dnsResolvers': 'dnspr'
  'Microsoft.Network/dnsResolvers/inboundEndpoints': 'in'
  'Microsoft.Network/dnsResolvers/outboundEndpoints': 'out'
  'Microsoft.Network/privateDnsZones': '<DNS domain name>'
  'Microsoft.Network/azureFirewalls': 'afw'
  //'Microsoft.Network/firewallPolicies': 'afwp'
  'Microsoft.Network/expressRouteCircuits': 'erc'
  'Microsoft.Network/expressRoutePorts': 'erd'
  //'Microsoft.Network/virtualNetworkGateways': 'ergw'
  'Microsoft.Cdn/profiles/afdEndpoints': 'fde'
  'Microsoft.Network/frontdoorWebApplicationFirewallPolicies': 'fdfp'
  'Microsoft.Network/frontDoors': 'afd'
  'Microsoft.Network/ipGroups': 'ipg'
  'Microsoft.Network/loadBalancers': 'lb'
  //'Microsoft.Network/loadBalancers': 'lbe'
  'Microsoft.Network/loadBalancers/inboundNatRules': 'rule'
  'Microsoft.Network/localNetworkGateways': 'lgw'
  'Microsoft.Network/natGateways': 'ng'
  'Microsoft.Network/networkInterfaces': 'nic'
  'Microsoft.Network/networkSecurityGroups': 'nsg'
  'Microsoft.Network/networkSecurityGroups/securityRules': 'nsgsr'
  'Microsoft.Network/networkWatchers': 'nw'
  'Microsoft.Network/privateLinkServices': 'pl'
  'Microsoft.Network/privateEndpoints': 'pep'
  'Microsoft.Network/publicIPAddresses': 'pip'
  'Microsoft.Network/publicIPPrefixes': 'ippre'
  'Microsoft.Network/routeFilters': 'rf'
  //'Microsoft.Network/virtualHubs': 'rtserv'
  'Microsoft.Network/routeTables': 'rt'
  'Microsoft.serviceEndPointPolicies': 'se'
  'Microsoft.Network/trafficManagerProfiles': 'traf'
  'Microsoft.Network/routeTables/routes': 'udr'
  'Microsoft.Network/virtualNetworks': 'vnet'
  'Microsoft.Network/virtualNetworkGateways': 'vgw'
  'Microsoft.Network/networkManagers': 'vnm'
  'Microsoft.Network/virtualNetworks/virtualNetworkPeerings': 'peer'
  'Microsoft.Network/virtualNetworks/subnets': 'snet'
  'Microsoft.Network/virtualWans': 'vwan'
  'Microsoft.Network/virtualHubs': 'vhub'

  // Security
  'Microsoft.Network/bastionHosts': 'bas'
  'Microsoft.KeyVault/vaults': 'kv'
  'Microsoft.KeyVault/managedHSMs': 'kvmhsm'
  'Microsoft.ManagedIdentity/userAssignedIdentities': 'id'
  'Microsoft.Compute/sshPublicKeys': 'sshkey'
  'Microsoft.Network/vpnGateways': 'vpng'
  'Microsoft.Network/vpnGateways/vpnConnections': 'vcn'
  'Microsoft.Network/vpnGateways/vpnSites': 'vst'
  'Microsoft.Network/firewallPolicies': 'waf'
  'Microsoft.Network/firewallPolicies/ruleGroups': 'wafrg'

  // Storage
  'Microsoft.StorSimple/managers': 'ssimp'
  'Microsoft.DataProtection/backupVaults': 'bvault'
  'Microsoft.DataProtection/backupVaults/backupPolicies': 'bkpol'
  'Microsoft.Storage/storageAccounts/fileServices/shares': 'share'
  'Microsoft.Storage/storageAccounts': 'st'
  'Microsoft.StorageSync/storageSyncServices': 'sss'

  // Virtual desktop infrastructure
  'Microsoft.DesktopVirtualization/hostPools': 'vdpool'
  'Microsoft.DesktopVirtualization/applicationGroups': 'vdag'
  'Microsoft.DesktopVirtualization/workspaces': 'vdws'
  'Microsoft.DesktopVirtualization/scalingPlans': 'vdscaling'
}
