
name: Release a new Bicep-Module-Version

on:
  pull_request:
    branches:
      - master
    types:
      - closed
   
jobs:
  create_release:
    if: github.event.pull_request.merged == true
    name: Create Release for Release-Version
    runs-on: ubuntu-latest

    outputs:
      version_tag: ${{ steps.create_release.outputs.result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
     
      - name: Create Release Version
        uses: actions/github-script@v5
        id: create_release
        env:
         BRANCH: ${{ github.ref_name }}
         VERSION: ${{ github.head_ref}}
        with:
          github-token: ${{ github.TOKEN }}
          script: |

              // Using API because git describe --abbrev=0 --tags doesn't work
              const versionRef = process.env.VERSION.match(/\d+[.]\d+/)[0]
              const references = await github.rest.git.listMatchingRefs({
                owner: context.repo.owner,
                repo: context.repo.repo,

                ref: `tags/${versionRef}`
              })

              console.log(references)

              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,

                ref: references.data.at(-1).ref.substr(5)
              });

              const versionTag = references.data.at(-1).ref.match(/\d+[.]\d+[.]\d+/)[0]
              console.log(versionTag)

              const release = await github.rest.repos.createRelease({
                 owner: context.repo.owner,
                 repo: context.repo.repo,

                 tag_name: versionTag,
                 target_commitish: process.env.BRANCH,
                 name: `Release v${versionTag}`,

                 make_latest: 'true',
                 generate_release_notes: true
              })

              console.log(release)
              return versionTag




  publish_bicep_release:
    needs: 
      - create_release
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/bicep.acr.publish.yaml
    secrets: inherit
    with:
      file_path:  ./modules/module.naming.bicep
      registry: bicepnamingpoc001

      image: module.naming
      version: ${{ needs.create_release.outputs.version_tag }}

      # Make release Module-Version immutable
      immutable: true